# Generated by Django 3.2.7 on 2021-12-05 02:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='cover')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('housing_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Town_House', 'Town House')], max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('admin_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Housing_Bath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baths', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Housing_Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Housing_People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField(default=0)),
                ('baths', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.housing_bath')),
                ('beds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.housing_bed')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.housing')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.housing_people')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default='False')),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.housing')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(blank=True, upload_to='gallery')),
                ('pic2', models.ImageField(blank=True, upload_to='gallery')),
                ('pic3', models.ImageField(blank=True, upload_to='gallery')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.housing')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('Air Conditioning', 'Air Conditioning'), ('Internet', 'Internet'), ('Disability Access', 'Disablity Access'), ('Intercom', 'Intercom'), ('Exterior Lighting', 'Exterior Lighting'), ('Security System', 'Security System'), ('Smoke Free', 'Smoke Free'), ('Washing Machine', 'Washing Machine'), ('Dryer', 'Dryer'), ('Furnished', 'Furnished'), ('Hardwood Floor', 'Hardwood Floor'), ('Dishwasher', 'Dishwasher'), ('Gym', 'Gym'), ('Pool', 'Pool'), ('Garden', 'Garden'), ('Patio/Balcony', 'Patio/Balcony'), ('Parking', 'Parking')], default='', max_length=193)),
                ('utilities', multiselectfield.db.fields.MultiSelectField(choices=[('Water', 'Water'), ('Electricity', 'Electricity'), ('Sewer', 'Sewer'), ('Gas', 'Gas'), ('Trash', 'Trash')], default='', max_length=33)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.housing')),
            ],
        ),
    ]
